### ISSUE TITLE
Keep connection alive

### ISSUE THREAD

**Issue by e0xify** [ronengr/hass_nuki_bt#75]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ronengr/hass_nuki_bt/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Seems that clicking once after an anmount of time not using the button, seems the modul to build up the connection first and then run the command.
This lacks in a delay of about 5-6 seconds before the door gets opened / closed.
Another press directly after, works immediatly.

any way to optimize to keep it connected all the time?

### Describe the solution you'd like

any way to optimize to keep it connected all the time?

### Describe alternatives you've considered

none

### Additional context

none

**Comment by ronengr** [comment]
The delay is due to Nuki lock's power saving algorithm.
As the lock is battery powered, they try to save as much power as possible. part of this is putting the lock to sleep and waking only from time to time to see if it got any communication for it.

You can try to change the "energy mode" in the lock configuration (via the Nuki app) to "performance mode". According to the manufacturer, this will reduce battery life and shorten the lock's response time.
Personally, I've tried this and didn't see a huge improvement or a big change in battery consumption.

There is another option i can think of:
I'm working on adding a button to force-query the nuki lock from HA. theoretically you can use this in an HA-automation, to call the lock periodically (and as this is an HA automation, you can control at what times you want to "keep alive" the connection). 
I wouldn't do it, unless this really bothers you, as this will probably drastically reduce the lock's battery life.
